In [1]:
import numpy as np


In [3]:
a=np.array([2,4,6])

In [4]:
print(a)

[2 4 6]


In [5]:
b=np.array([[1,2],[3,4],[5,6]])
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
b[0]

array([1, 2])

In [9]:
b.ndim

2

In [11]:
b.itemsize

4

In [12]:
a.dtype

dtype('int32')

In [15]:
b=np.array([[1,2],[3,4],[5,6]],dtype=np.float)
print(b)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [16]:
b.size

6

In [18]:
b.shape

(3, 2)

In [19]:
b=np.array([[1,2],[3,4],[5,6]],dtype=np.complex64)
print(b)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]
 [5.+0.j 6.+0.j]]


In [21]:
#placeholder nos
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((3,4),dtype=np.int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.arange(1,5)     #initializes like done with for loop

array([1, 2, 3, 4])

In [27]:
np.arange(1,5,2)     #with the step of 2

array([1, 3])

In [28]:
np.linspace(1,5,10)     #linearly space

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [29]:
a.reshape((3,1))

array([[2],
       [4],
       [6]])

In [30]:
a.ravel()   #flattens the array

array([2, 4, 6])

In [31]:
a.min()

2

In [32]:
a.max()

6

In [33]:
a.sum()

12

In [35]:
b.sum(axis=0)  #sum per columnn

array([ 9.+0.j, 12.+0.j], dtype=complex64)

In [39]:
b.sum(axis=1)    #sum  per row


array([ 3.+0.j,  7.+0.j, 11.+0.j], dtype=complex64)

In [41]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974])

In [42]:
#standard deviation
np.std(a)

1.632993161855452

In [ ]:
#basic Mathematical operation

In [50]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])


In [51]:
c

array([[1, 2],
       [3, 4]])

In [52]:
d

array([[5, 6],
       [7, 8]])

In [53]:
c+d

array([[ 6,  8],
       [10, 12]])

In [54]:
c*d

array([[ 5, 12],
       [21, 32]])

In [55]:
c/d

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [57]:
c.dot(d)

array([[19, 22],
       [43, 50]])